import type { CSSProperties } from 'react';

/* Shared constants referenced by the style maps below. */
export const TEAL = "var(--dashboard-primary)";
export const CARD_SHADOW = "0 8px 28px rgba(10, 92, 131, 0.08)";

export const shell: Record<string, CSSProperties> = {
  sidebarProfile: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minHeight: 56,
    flexShrink: 0,
    margin: "0 14px",
    padding: "10px 12px",
    backgroundColor: "#f3f4f6",
    borderRadius: 14,
    boxSizing: "border-box",
  },
  profileAvatar: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    backgroundColor: "#cbd5e1",
    color: TEAL,
    fontSize: 11,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  profileName: {
    fontSize: 12,
    fontWeight: 700,
    color: "#0f172a",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  profileEmail: {
    fontSize: 10,
    color: "#94a3b8",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
};

export const overview: Record<string, CSSProperties> = {
  page: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  statsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 16,
  },
  statCard: {
    borderRadius: 22,
    padding: "20px 22px",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    gap: 16,
    minHeight: 96,
    border: "none",
    width: "100%",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  statIcon: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    backgroundColor: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  statLabel: {
    fontSize: 13,
    fontWeight: 600,
    opacity: 0.92,
  },
  statValue: {
    fontSize: 28,
    fontWeight: 800,
    lineHeight: 1.15,
    marginTop: 2,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.35fr) minmax(280px, 0.75fr)",
    gap: 16,
    alignItems: "start",
  },
  patientCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: "20px 22px 12px",
    boxShadow: CARD_SHADOW,
  },
  patientHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sectionTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 800,
    color: "#0f172a",
  },
  pageChevron: {
    width: 28,
    height: 28,
    borderRadius: 8,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    color: "#64748b",
    fontSize: 18,
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    fontSize: 12,
    fontWeight: 600,
    color: "#64748b",
    padding: "10px 8px",
    borderBottom: "1px solid #f1f5f9",
  },
  td: {
    padding: "14px 8px",
    fontSize: 13,
    borderBottom: "none",
    verticalAlign: "middle",
  },
  checkbox: {
    width: 14,
    height: 14,
    accentColor: TEAL,
    cursor: "pointer",
  },
  rowDots: {
    color: "#94a3b8",
    fontSize: 18,
    letterSpacing: 1,
    lineHeight: 1,
  },
  dot: {
    width: 11,
    height: 11,
    borderRadius: "50%",
    display: "inline-block",
  },
  rightCol: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  widget: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 18,
    boxShadow: CARD_SHADOW,
  },
  calNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  calMonthButton: {
    border: "1px solid #86efac",
    backgroundColor: "#dcfce7",
    color: "#166534",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  calPicker: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    marginBottom: 10,
    padding: "8px 12px",
    backgroundColor: "#334155",
    borderRadius: 8,
  },
  calPickerColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 2,
  },
  calPickerArrow: {
    border: "none",
    backgroundColor: "transparent",
    color: "#cbd5e1",
    height: 18,
    cursor: "pointer",
  },
  calPickerOption: {
    border: "none",
    backgroundColor: "transparent",
    color: "#e2e8f0",
    borderRadius: 4,
    padding: "4px 6px",
    fontSize: 11,
    cursor: "pointer",
  },
  calPickerOptionActive: {
    border: "none",
    backgroundColor: "#6366c7",
    color: "#ffffff",
    borderRadius: 4,
    padding: "4px 6px",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
  },
  calGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 4,
  },
  calDow: {
    textAlign: "center",
    fontSize: 10,
    fontWeight: 700,
    color: "#94a3b8",
    padding: "4px 0",
  },
  calDay: {
    border: "none",
    background: "transparent",
    height: 32,
    borderRadius: 16,
    fontSize: 12,
    color: "#334155",
    cursor: "pointer",
    padding: 0,
  },
  calDayActive: {
    backgroundColor: TEAL,
    color: "#ffffff",
    fontWeight: 700,
  },
  todoHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  addNotesBtn: {
    border: "1.5px solid #0ea5e9",
    backgroundColor: "#effaff",
    color: "#0369a1",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  editNotesBtn: {
    border: "1.5px solid #f59e0b",
    backgroundColor: "#fffbeb",
    color: "#b45309",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  doneNotesBtn: {
    border: "1.5px solid #14b8a6",
    backgroundColor: "#ccfbf1",
    color: "#0f766e",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  addNoteInput: {
    flex: 1,
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "8px 10px",
    fontSize: 13,
    outline: "none",
  },
  cancelNotesBtn: {
    border: "1px solid #cbd5e1",
    backgroundColor: "#f8fafc",
    color: "#475569",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  todoList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    maxHeight: 280,
    overflowY: "auto",
  },
  todoItem: {
    margin: 0,
  },
  todoItemEditing: {
    border: "1px dashed #2dd4bf",
    backgroundColor: "#f0fdfa",
    borderRadius: 8,
    padding: "6px 8px",
  },
  todoLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "#334155",
    cursor: "pointer",
  },
  todoActions: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 },
  todoDeleteBtn: {
    border: "1px solid #fca5a5",
    backgroundColor: "#fff1f2",
    color: "#dc2626",
    borderRadius: 6,
    padding: "3px 7px",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
  },
};

export const manage: Record<string, CSSProperties> = {
  layout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.15fr) minmax(320px, 0.85fr)",
    gap: 20,
    alignItems: "start",
  },
  listCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: "18px 20px 12px",
    boxShadow: CARD_SHADOW,
  },
  listHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 8,
  },
  listTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 800,
    color: "#0f172a",
  },
  listHint: {
    margin: "4px 0 0",
    fontSize: 12,
    color: "#64748b",
  },
  tableScroll: {
    overflowX: "auto",
  },
  filterRange: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  filterRangeField: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  filterRangeLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: "#64748b",
  },
  filterRangeInput: {
    border: "1px solid #dbe3ec",
    borderRadius: 8,
    padding: "6px 8px",
    fontSize: 12,
    color: "#0f172a",
    backgroundColor: "#ffffff",
  },
  orderTime: {
    flexShrink: 0,
    minWidth: 58,
    fontSize: 12,
    fontWeight: 700,
    color: "#64748b",
    fontVariantNumeric: "tabular-nums",
  },
  rightCol: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  orderCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 20,
    border: "1px solid #e2e8f0",
  },
  orderHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  panelTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 800,
    color: "#0f172a",
  },
  dateNavigator: { display: "flex", alignItems: "center", gap: 8 },
  dateNavBtn: {
    width: 28,
    height: 28,
    border: "none",
    backgroundColor: "transparent",
    color: "#64748b",
    fontSize: 18,
    padding: 0,
    cursor: "pointer",
  },
  dateNavBtnDisabled: {
    width: 28,
    height: 28,
    border: "none",
    backgroundColor: "transparent",
    color: "#cbd5e1",
    fontSize: 18,
    padding: 0,
    cursor: "not-allowed",
  },
  dateInput: {
    width: 126,
    border: "1px solid #dbe3ec",
    borderRadius: 8,
    padding: "7px 8px",
    color: "#0f172a",
    backgroundColor: "#ffffff",
    fontSize: 12,
    fontFamily: "inherit",
    textAlign: "center",
    cursor: "pointer",
  },
  orderBox: {
    backgroundColor: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 14,
    marginBottom: 12,
  },
  patientMeta: {
    marginBottom: 12,
  },
  // Each day is its own card with an opaque, tinted header. The header sticks
  // while its day scrolls, so a multi-date list never reads as one grey block:
  // the tint marks where one day ends and the next begins, and text scrolling
  // underneath is hidden by the header instead of clipped by a stray rule.
  orderScroll: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    maxHeight: "min(560px, 62vh)",
    overflowY: "auto",
    paddingRight: 6,
  },
  orderDayGroup: {
    // Deliberately no `overflow: hidden` — it would break the sticky header.
    backgroundColor: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
  },
  orderDayHeader: {
    position: "sticky",
    top: 0,
    zIndex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "9px 12px",
    backgroundColor: "#e8f1f7",
    borderBottom: "1px solid #cbd9e4",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    fontSize: 14,
    fontWeight: 800,
    color: "#0f172a",
  },
  orderDayLabel: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    minWidth: 0,
  },
  orderDayRelative: {
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: TEAL,
  },
  orderDayCount: {
    flexShrink: 0,
    fontSize: 12,
    fontWeight: 700,
    color: "#475569",
    backgroundColor: "#ffffff",
    border: "1px solid #cbd9e4",
    borderRadius: 999,
    padding: "1px 8px",
  },
  orderDayBody: {
    display: "flex",
    flexDirection: "column",
  },
  dateClearBtn: {
    border: "1px solid #dbe3ec",
    backgroundColor: "#ffffff",
    color: "#0369a1",
    borderRadius: 8,
    padding: "6px 10px",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  orderLine: {
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 14,
    lineHeight: 1.55,
    color: "#334155",
    backgroundColor: "#ffffff",
  },
  noteArea: {
    width: "100%",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 10,
    fontSize: 13,
    resize: "vertical",
    marginBottom: 12,
    boxSizing: "border-box",
  },
  orderActions: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  addBtn: {
    border: `1.5px solid ${TEAL}`,
    backgroundColor: "#ffffff",
    color: TEAL,
    borderRadius: 10,
    padding: "8px 18px",
    fontWeight: 700,
    cursor: "pointer",
  },
  submitBtn: {
    border: "none",
    backgroundColor: TEAL,
    color: "#ffffff",
    borderRadius: 10,
    padding: "8px 20px",
    fontWeight: 700,
    cursor: "pointer",
  },
  cancelBtn: {
    border: "1px solid #cbd5e1",
    backgroundColor: "#ffffff",
    color: "#64748b",
    borderRadius: 10,
    padding: "8px 16px",
    fontWeight: 700,
    cursor: "pointer",
  },
  aiCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    border: "1px solid #e2e8f0",
    overflow: "hidden",
  },
  aiHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 16px",
    backgroundColor: "#f1eaff",
  },
  aiTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 800,
    color: "#7c00b8",
  },
  aiBadge: {
    backgroundColor: "#d3a0f5",
    color: "#7c00b8",
    fontSize: 11,
    fontWeight: 700,
    padding: "4px 14px",
    borderRadius: 6,
  },
  aiBody: {
    padding: "14px 16px 18px",
  },
  aiText: {
    margin: "0 0 14px",
    fontSize: 13,
    lineHeight: 1.55,
    color: "#1e293b",
  },
  aiEditor: {
    width: "100%",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 10,
    fontSize: 13,
    marginBottom: 12,
    boxSizing: "border-box",
    backgroundColor: "#f8fafc",
  },
  aiActions: {
    display: "flex",
    gap: 10,
  },
  aiLink: {
    border: "1px solid #9cc8ff",
    backgroundColor: "#ffffff",
    color: "#0066cc",
    fontSize: 12,
    fontWeight: 700,
    borderRadius: 6,
    padding: "6px 14px",
    cursor: "pointer",
  },
  dotsBtn: {
    border: "none",
    background: "transparent",
    cursor: "pointer",
    color: "#64748b",
    fontSize: 18,
    padding: "4px 8px",
    lineHeight: 1,
  },
  rowMenu: {
    position: "absolute",
    right: 0,
    top: "100%",
    zIndex: 12,
    backgroundColor: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    boxShadow: "0 8px 20px rgba(15, 23, 42, 0.1)",
    minWidth: 180,
    overflow: "hidden",
  },
  rowMenuItem: {
    display: "block",
    width: "100%",
    textAlign: "left",
    border: "none",
    background: "transparent",
    padding: "10px 12px",
    fontSize: 12,
    fontWeight: 600,
    color: "#334155",
    cursor: "pointer",
  },
  // Order rows: the time is a fixed column so every order lines up under its
  // day heading, and the order text gets the readable size.
  orderRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    padding: "8px 12px",
  },
  orderEditRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
  },
  /** Hairline between two orders of the *same* day, so a long day stays scannable. */
  orderRowDivided: {
    borderTop: "1px solid #eef2f7",
  },
  orderText: {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    lineHeight: 1.6,
    color: "#1e293b",
    overflowWrap: "break-word",
  },
  orderEditInput: {
    flex: 1,
    border: "1px solid #cbd5e1",
    borderRadius: 8,
    padding: "9px 10px",
    fontSize: 14,
  },
  removeOrderBtn: {
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#dc2626",
    borderRadius: 6,
    width: 28,
    height: 28,
    padding: 0,
    cursor: "pointer",
  },
  calOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(15, 23, 42, 0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
  },
  calModal: {
    width: 340,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    boxShadow: "0 16px 40px rgba(15, 23, 42, 0.18)",
  },
  calHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  calTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 800,
    color: "#0f172a",
  },
  calClose: {
    border: "none",
    background: "transparent",
    cursor: "pointer",
    color: "#94a3b8",
    fontSize: 16,
    padding: 4,
  },
  calNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  calNavBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    border: "1px solid #e2e8f0",
    background: "#fff",
    cursor: "pointer",
    padding: 0,
  },
  calNavBtnDisabled: {
    width: 28,
    height: 28,
    borderRadius: 6,
    border: "1px solid #e2e8f0",
    background: "#fff",
    color: "#cbd5e1",
    cursor: "not-allowed",
    padding: 0,
  },
  calMonth: {
    fontSize: 14,
    fontWeight: 700,
    color: "#0f172a",
  },
  calGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 4,
  },
  calDow: {
    textAlign: "center",
    fontSize: 10,
    fontWeight: 700,
    color: "#94a3b8",
    padding: "4px 0",
  },
  calDay: {
    border: "none",
    background: "transparent",
    height: 36,
    borderRadius: 6,
    fontSize: 12,
    color: "#334155",
    cursor: "pointer",
    padding: 0,
  },
  calDayDisabled: {
    color: "#cbd5e1",
    cursor: "not-allowed",
  },
  calDaySelected: {
    backgroundColor: TEAL,
    color: "#ffffff",
    fontWeight: 700,
    borderRadius: 18,
  },
};

export const requests: Record<string, CSSProperties> = {
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: "24px 24px 16px",
    boxShadow: CARD_SHADOW,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    fontSize: 12,
    fontWeight: 700,
    color: TEAL,
    padding: "12px 14px",
    backgroundColor: "#f1f5f9",
    borderBottom: "1px solid #e2e8f0",
  },
  td: {
    padding: "14px",
    fontSize: 13,
    borderBottom: "1px solid #f1f5f9",
    verticalAlign: "middle",
  },
  primary: {
    fontWeight: 700,
    color: "#0f172a",
  },
  secondary: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
};

export const review: Record<string, CSSProperties> = {
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    padding: 24,
  },
  shell: {
    display: "flex",
    alignItems: "stretch",
    maxWidth: 1080,
    width: "100%",
    maxHeight: "90vh",
    position: "relative",
  },
  ordersPanel: {
    width: 280,
    flexShrink: 0,
    backgroundColor: "#ffffff",
    borderRadius: "16px 0 0 16px",
    padding: 16,
    display: "flex",
    flexDirection: "column",
    border: "1px solid #e2e8f0",
    borderRight: "none",
  },
  ordersTitle: {
    margin: "0 0 12px",
    fontSize: 15,
    fontWeight: 800,
    color: "#0f172a",
  },
  ordersScroll: {
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    paddingRight: 4,
  },
  orderCard: {
    backgroundColor: "#ecfdf5",
    borderRadius: 10,
    padding: 12,
  },
  orderWhen: {
    fontSize: 11,
    fontWeight: 700,
    color: "#0f172a",
  },
  orderTime: {
    fontSize: 11,
    color: "#64748b",
    marginBottom: 6,
  },
  orderDoctor: {
    fontSize: 13,
    fontWeight: 800,
    color: "#0f172a",
  },
  orderList: {
    margin: 0,
    paddingLeft: 16,
    fontSize: 12,
    color: "#334155",
    lineHeight: 1.45,
  },
  collapseBtn: {
    position: "absolute",
    left: 268,
    top: "50%",
    transform: "translateY(-50%)",
    width: 24,
    height: 24,
    borderRadius: "50%",
    border: "1px solid #e2e8f0",
    backgroundColor: "#ffffff",
    cursor: "pointer",
    zIndex: 2,
    padding: 0,
    fontSize: 14,
  },
  mainPanel: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    boxShadow: "0 20px 50px rgba(15, 23, 42, 0.18)",
  },
  header: {
    backgroundColor: TEAL,
    color: "#ffffff",
    padding: "14px 18px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  headerTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 800,
  },
  headerId: {
    fontSize: 12,
    opacity: 0.9,
    marginTop: 2,
  },
  headerClose: {
    border: "none",
    background: "transparent",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: 16,
    padding: 4,
  },
  body: {
    padding: 18,
    overflowY: "auto",
    flex: 1,
  },
  infoBanner: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    backgroundColor: "#e0f2fe",
    color: "#0369a1",
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 12,
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: 800,
    color: "#0f172a",
    marginBottom: 8,
  },
  patientGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 10,
    marginBottom: 16,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  fieldLabel: {
    fontSize: 11,
    color: "#64748b",
  },
  fieldInput: {
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "8px 10px",
    fontSize: 13,
    backgroundColor: "#f8fafc",
    color: "#0f172a",
  },
  submittedCard: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    border: "1px solid #e2e8f0",
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    backgroundColor: "#f8fafc",
  },
  aiHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  hideOrdersBtn: {
    border: `1px solid ${TEAL}`,
    backgroundColor: "#ffffff",
    color: TEAL,
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  summaryBox: {
    backgroundColor: "#ecfdf5",
    borderRadius: 10,
    padding: 12,
    fontSize: 13,
    lineHeight: 1.6,
    color: "#334155",
    marginBottom: 12,
  },
  summaryEditor: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #bbf7d0",
    borderRadius: 10,
    padding: 12,
    fontSize: 13,
    lineHeight: 1.6,
    marginBottom: 12,
    backgroundColor: "#f0fdf4",
  },
  aiActions: {
    display: "flex",
    gap: 10,
  },
  outlineBtn: {
    border: `1px solid ${TEAL}`,
    backgroundColor: "#ffffff",
    color: TEAL,
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    padding: "12px 18px 16px",
    borderTop: "1px solid #f1f5f9",
  },
  cancelBtn: {
    border: "1px solid #cbd5e1",
    backgroundColor: "#e2e8f0",
    color: "#334155",
    borderRadius: 8,
    padding: "8px 18px",
    fontWeight: 700,
    cursor: "pointer",
  },
  approveBtn: {
    border: "none",
    backgroundColor: TEAL,
    color: "#ffffff",
    borderRadius: 8,
    padding: "8px 20px",
    fontWeight: 700,
    cursor: "pointer",
  },
};
