import type { CSSProperties } from 'react';

/* Shared constants referenced by the style maps below. */
export const TEAL = 'var(--dashboard-primary)';

export const ui: Record<string, CSSProperties> = {
  layout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.1fr) minmax(340px, 0.9fr)',
    gap: 20,
    alignItems: 'start',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 18,
    border: '1px solid #e5e7eb',
  },
  sectionTitle: { margin: '0 0 12px', fontSize: 20, fontWeight: 800, color: '#0f172a' },
  muted: { color: '#64748b', fontSize: 13, marginTop: 0 },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    textAlign: 'left',
    fontSize: 12,
    fontWeight: 700,
    color: 'var(--c4w-color-primary)',
    backgroundColor: 'var(--c4w-color-primary-soft)',
    padding: '12px 14px',
    borderBottom: '1px solid var(--c4w-color-border)',
    whiteSpace: 'nowrap',
  },
  td: { padding: '12px 8px', fontSize: 13, borderBottom: '1px solid #f8fafc', verticalAlign: 'middle' },
  dot: { width: 10, height: 10, borderRadius: '50%', display: 'inline-block' },
  viewBtn: {
    border: 'none',
    backgroundColor: TEAL,
    color: '#ffffff',
    borderRadius: 8,
    padding: '6px 14px',
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
  },
  detailCol: { display: 'flex', flexDirection: 'column', gap: 16 },
  patientHeader: { display: 'flex', gap: 14, alignItems: 'center' },
  patientAvatar: {
    width: 64,
    height: 64,
    borderRadius: '50%',
    color: '#ffffff',
    fontWeight: 800,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  metaRow: { display: 'flex', flexWrap: 'wrap', gap: 12, fontSize: 12, color: '#64748b', marginTop: 6 },
  orderCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    border: '1px solid #e2e8f0',
  },
  orderBox: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: 12,
  },
  orderHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  dateNav: { display: 'flex', alignItems: 'center', gap: 8 },
  navChevron: {
    width: 28,
    height: 28,
    borderRadius: 8,
    border: '1px solid #cbd5e1',
    background: '#fff',
    cursor: 'pointer',
    padding: 0,
  },
  orderMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  viewedBadge: {
    backgroundColor: '#bbf7d0',
    color: '#166534',
    borderRadius: 999,
    padding: '4px 10px',
    fontSize: 11,
    fontWeight: 700,
  },
  orderList: { margin: '0 0 14px', paddingLeft: 18, fontSize: 13, color: '#334155', lineHeight: 1.5 },
  input: {
    border: '1px solid #cbd5e1',
    borderRadius: 8,
    padding: '8px 10px',
    fontSize: 13,
    background: '#fff',
  },
  aiCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
  },
  aiHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 16px',
    backgroundColor: '#f1eaff',
  },
  aiTitle: { fontWeight: 800, fontSize: 14, color: '#7c00b8' },
  aiBadge: {
    backgroundColor: '#d3a0f5',
    color: '#7c00b8',
    fontSize: 11,
    fontWeight: 700,
    padding: '4px 14px',
    borderRadius: 6,
  },
  aiBody: { padding: '14px 16px 18px' },
  aiText: { margin: 0, fontSize: 13, lineHeight: 1.55, color: '#1e293b' },
  primaryBtn: {
    border: 'none',
    backgroundColor: TEAL,
    color: '#ffffff',
    borderRadius: 8,
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  outlineBtn: {
    border: '1px solid #0284c7',
    backgroundColor: '#ffffff',
    color: '#0284c7',
    borderRadius: 8,
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
  },
  tableWrap: {
    border: '1px solid #e2e8f0',
    borderRadius: 12,
    overflow: 'hidden',
  },
  thBlue: {
    textAlign: 'left',
    fontSize: 12,
    fontWeight: 700,
    color: 'var(--c4w-color-primary)',
    padding: '12px 14px',
    backgroundColor: 'var(--c4w-color-primary-soft)',
    borderBottom: '1px solid var(--c4w-color-border)',
  },
  idLink: {
    border: 'none',
    background: 'transparent',
    color: '#0284c7',
    fontWeight: 700,
    cursor: 'pointer',
    padding: 0,
    fontSize: 13,
  },
  badgeAdmitted: {
    display: 'inline-block',
    backgroundColor: '#dbeafe',
    color: '#1d4ed8',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  badgeDischarged: {
    display: 'inline-block',
    backgroundColor: '#e2e8f0',
    color: '#1e3a5f',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 40,
  },
  fieldLabel: { fontSize: 12, color: '#64748b', fontWeight: 600 },
  modalActions: { display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 8 },
  modalWide: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 24,
    width: 640,
    maxWidth: '94%',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  modalHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  closeX: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    color: '#94a3b8',
    fontSize: 16,
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 12,
    marginBottom: 8,
  },
  detailValue: { fontSize: 14, fontWeight: 700, color: '#0f172a' },
  subhead: { margin: '16px 0 8px', fontSize: 14, fontWeight: 800, color: '#0f172a' },
  triageGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 8,
  },
  triageCell: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: 10,
  },
  notesBox: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 13,
    color: '#334155',
    lineHeight: 1.5,
  },
  doctorList: { margin: '0 0 8px', paddingLeft: 18, fontSize: 13, color: '#0f172a' },
  addDoctorRow: { display: 'flex', gap: 8, alignItems: 'center', marginTop: 8 },
  nameBtn: {
    border: 'none',
    background: 'transparent',
    padding: 0,
    fontWeight: 600,
    color: '#0f172a',
    cursor: 'pointer',
    fontSize: 13,
  },
  dateInput: {
    border: '1px solid #cbd5e1',
    borderRadius: 8,
    padding: '4px 8px',
    fontSize: 12,
    fontWeight: 600,
  },
};
