import type { CSSProperties } from 'react';

/* Shared constants referenced by the style maps below. */
export const TEAL = 'var(--dashboard-primary)';

export const ui: Record<string, CSSProperties> = {
  layout: {
    // The Claims Processor overview grid: two equal columns, 24px gutter.
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 24,
    alignItems: 'start',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 18,
    border: '1px solid #e5e7eb',
  },
  sectionTitle: { margin: '0 0 12px', fontSize: 20, fontWeight: 800, color: '#0f172a' },
  muted: { color: '#64748b', fontSize: 13, marginTop: 0 },
  detailCol: { display: 'flex', flexDirection: 'column', gap: 24 },
  primaryBtn: {
    border: 'none',
    backgroundColor: TEAL,
    color: '#ffffff',
    borderRadius: 8,
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  outlineBtn: {
    border: '1px solid #0284c7',
    backgroundColor: '#ffffff',
    color: '#0284c7',
    borderRadius: 8,
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
  },
  badgeAdmitted: {
    display: 'inline-block',
    backgroundColor: '#dbeafe',
    color: '#1d4ed8',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  badgeDischarged: {
    display: 'inline-block',
    backgroundColor: '#e2e8f0',
    color: '#1e3a5f',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  badgeEr: {
    display: 'inline-block',
    backgroundColor: '#ffedd5',
    color: '#c2410c',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 40,
  },
  fieldLabel: { fontSize: 12, color: '#64748b', fontWeight: 600 },
  modalActions: { display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 8 },
  modalWide: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 24,
    width: 640,
    maxWidth: '94%',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  modalHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  closeX: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    color: '#94a3b8',
    fontSize: 16,
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 12,
    marginBottom: 8,
  },
  detailValue: { fontSize: 14, fontWeight: 700, color: '#0f172a' },
  subhead: { margin: '16px 0 8px', fontSize: 14, fontWeight: 800, color: '#0f172a' },
  triageGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 8,
  },
  triageCell: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: 10,
  },
  notesBox: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 13,
    color: '#334155',
    lineHeight: 1.5,
  },
  doctorList: { margin: '0 0 8px', paddingLeft: 18, fontSize: 13, color: '#0f172a' },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    marginTop: 4,
    padding: '8px 10px',
    fontSize: 14,
    color: '#0f172a',
    backgroundColor: '#ffffff',
    border: '1px solid #cbd5e1',
    borderRadius: 8,
    outline: 'none',
    fontFamily: 'inherit',
  },
  triageInput: {
    width: '100%',
    boxSizing: 'border-box',
    marginTop: 2,
    padding: '2px 0',
    fontSize: 14,
    fontWeight: 700,
    color: '#0f172a',
    background: 'transparent',
    border: 'none',
    borderBottom: '1px dashed #cbd5e1',
    outline: 'none',
    fontFamily: 'inherit',
  },
  required: { color: '#dc2626', marginLeft: 2 },
  doctorRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: '8px 10px',
    fontSize: 13,
    fontWeight: 600,
    color: '#0f172a',
  },
  doctorRole: { fontSize: 11, fontWeight: 600, color: '#64748b', marginLeft: 6 },
  removeBtn: {
    border: 'none',
    background: 'transparent',
    color: '#dc2626',
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
    padding: '2px 4px',
  },
  addRow: { display: 'flex', gap: 8, alignItems: 'center', marginTop: 8 },
};

export const addPatient: Record<string, CSSProperties> = {
  modal: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    width: 720,
    maxWidth: '94%',
    maxHeight: '92vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    boxShadow: '0 24px 48px rgba(15, 23, 42, 0.18)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    padding: '20px 24px 16px',
    borderBottom: '1px solid #e2e8f0',
  },
  titleRow: { display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
  title: { margin: 0, fontSize: 20, fontWeight: 800, color: '#0f172a' },
  subtitle: { margin: '4px 0 0', fontSize: 13, color: '#64748b' },
  body: {
    padding: '20px 24px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    backgroundColor: '#f8fafc',
  },
  section: {
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: 14,
    padding: 16,
  },
  sectionHeader: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 },
  sectionIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    display: 'grid',
    placeItems: 'center',
    fontSize: 15,
    backgroundColor: '#e0f2fe',
    color: '#0369a1',
    flexShrink: 0,
  },
  sectionIconImg: { width: 18, height: 18, objectFit: 'contain', display: 'block' },
  sectionTitle: { margin: 0, fontSize: 14, fontWeight: 800, color: '#0f172a' },
  sectionHint: { margin: '2px 0 0', fontSize: 12, color: '#64748b' },
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 },
  grid4: { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 10 },
  label: { display: 'block', fontSize: 12, fontWeight: 700, color: '#475569', marginBottom: 6 },
  required: { color: '#dc2626', marginLeft: 3 },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    height: 40,
    padding: '0 12px',
    fontSize: 14,
    color: '#0f172a',
    backgroundColor: '#ffffff',
    border: '1px solid #cbd5e1',
    borderRadius: 10,
    outline: 'none',
    fontFamily: 'inherit',
  },
  textarea: {
    width: '100%',
    boxSizing: 'border-box',
    minHeight: 84,
    padding: '10px 12px',
    fontSize: 14,
    lineHeight: 1.5,
    color: '#0f172a',
    backgroundColor: '#ffffff',
    border: '1px solid #cbd5e1',
    borderRadius: 10,
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
  },
  segmented: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 4,
    padding: 4,
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
    height: 40,
    boxSizing: 'border-box',
  },
  segment: {
    border: 'none',
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 700,
    color: '#64748b',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  segmentActive: {
    backgroundColor: '#ffffff',
    color: '#0f172a',
    boxShadow: '0 1px 3px rgba(15, 23, 42, 0.12)',
  },
  vital: {
    display: 'block',
    minWidth: 0,
    boxSizing: 'border-box',
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 10,
    padding: '8px 10px',
  },
  vitalLabel: {
    display: 'block',
    fontSize: 11,
    fontWeight: 700,
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  vitalRow: { display: 'flex', alignItems: 'baseline', gap: 4, marginTop: 4, minWidth: 0 },
  vitalValue: {
    flex: 1,
    minWidth: 0,
    fontSize: 16,
    fontWeight: 700,
    color: '#0f172a',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  readValue: {
    minHeight: 40,
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    padding: '0 12px',
    fontSize: 14,
    fontWeight: 700,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 10,
  },
  readNotes: {
    minHeight: 60,
    boxSizing: 'border-box',
    padding: '10px 12px',
    fontSize: 14,
    lineHeight: 1.5,
    color: '#334155',
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 10,
    whiteSpace: 'pre-wrap',
  },
  vitalInput: {
    flex: 1,
    width: 0,
    minWidth: 0,
    padding: 0,
    fontSize: 16,
    fontWeight: 700,
    color: '#0f172a',
    background: 'transparent',
    border: 'none',
    outline: 'none',
    fontFamily: 'inherit',
  },
  vitalUnit: { fontSize: 11, fontWeight: 600, color: '#94a3b8', whiteSpace: 'nowrap' },
  doctorCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 12px',
    border: '1px solid #e2e8f0',
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    fontSize: 12,
    fontWeight: 800,
    flexShrink: 0,
  },
  doctorName: { fontSize: 13, fontWeight: 700, color: '#0f172a' },
  doctorMeta: { fontSize: 11, color: '#64748b', marginTop: 1 },
  removeIcon: {
    marginLeft: 'auto',
    width: 28,
    height: 28,
    borderRadius: 8,
    border: '1px solid #fecaca',
    backgroundColor: '#fef2f2',
    color: '#dc2626',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    display: 'grid',
    placeItems: 'center',
  },
  emptyDoctors: {
    padding: '12px',
    border: '1px dashed #cbd5e1',
    borderRadius: 10,
    fontSize: 12,
    color: '#64748b',
    textAlign: 'center',
  },
  error: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    borderRadius: 10,
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#b91c1c',
    fontSize: 13,
    fontWeight: 600,
  },
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    padding: '14px 24px',
    borderTop: '1px solid #e2e8f0',
    backgroundColor: '#ffffff',
  },
};
