import type { CSSProperties } from 'react';

/* Shared constants referenced by the style maps below. */
export const TEAL = 'var(--dashboard-primary)';

export const ui: Record<string, CSSProperties> = {
  layout: {
    // The Claims Processor overview grid: two equal columns, 24px gutter.
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 24,
    alignItems: 'start',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 18,
    border: '1px solid #e5e7eb',
  },
  sectionTitle: { margin: '0 0 12px', fontSize: 20, fontWeight: 800, color: '#0f172a' },
  muted: { color: '#64748b', fontSize: 13, marginTop: 0 },
  detailCol: { display: 'flex', flexDirection: 'column', gap: 24 },
  primaryBtn: {
    border: 'none',
    backgroundColor: TEAL,
    color: '#ffffff',
    borderRadius: 8,
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  outlineBtn: {
    border: '1px solid #0284c7',
    backgroundColor: '#ffffff',
    color: '#0284c7',
    borderRadius: 8,
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
  },
  badgeAdmitted: {
    display: 'inline-block',
    backgroundColor: '#dbeafe',
    color: '#1d4ed8',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  badgeDischarged: {
    display: 'inline-block',
    backgroundColor: '#e2e8f0',
    color: '#1e3a5f',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  badgeEr: {
    display: 'inline-block',
    backgroundColor: '#ffedd5',
    color: '#c2410c',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 40,
  },
  fieldLabel: { fontSize: 12, color: '#64748b', fontWeight: 600 },
  modalActions: { display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 8 },
  modalWide: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 24,
    width: 640,
    maxWidth: '94%',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  modalHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  closeX: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    color: '#94a3b8',
    fontSize: 16,
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 12,
    marginBottom: 8,
  },
  detailValue: { fontSize: 14, fontWeight: 700, color: '#0f172a' },
  subhead: { margin: '16px 0 8px', fontSize: 14, fontWeight: 800, color: '#0f172a' },
  triageGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 8,
  },
  triageCell: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: 10,
  },
  notesBox: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 13,
    color: '#334155',
    lineHeight: 1.5,
  },
  doctorList: { margin: '0 0 8px', paddingLeft: 18, fontSize: 13, color: '#0f172a' },
};
