import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  tableCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
  },
  thRow: {
    backgroundColor: 'var(--c4w-color-primary-soft)',
    borderBottom: '1px solid var(--c4w-color-border)',
  },
  th: {
    padding: '10px 16px',
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--c4w-color-primary)',
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  tr: {
    borderBottom: '1px solid #f1f5f9',
  },
  td: {
    padding: '12px 16px',
  },
  requestActionCell: {
    width: '20%',
    textAlign: 'right',
    whiteSpace: 'nowrap',
  },
  /** Date + time on one line keep request rows compact. */
  dateCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    whiteSpace: 'nowrap',
  },
  dateText: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#334155',
  },
  /** Dot between the date and the time. */
  dateSeparator: {
    width: '3px',
    height: '3px',
    borderRadius: '50%',
    backgroundColor: '#cbd5e1',
  },
  timeText: {
    fontSize: '12px',
    color: '#94a3b8',
  },
  paginationRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    borderTop: '1px solid #e2e8f0',
  },
  paginationText: {
    fontSize: '12px',
    color: '#64748b',
  },
  paginationControls: {
    display: 'flex',
    gap: '4px',
    alignItems: 'center',
  },
  pageArrowBtn: {
    border: '1px solid #e2e8f0',
    backgroundColor: '#ffffff',
    borderRadius: '4px',
    padding: '4px 8px',
    cursor: 'pointer',
  },
  pageNumberBtn: {
    minWidth: '32px',
    height: '32px',
    border: '1px solid #e2e8f0',
    backgroundColor: 'transparent',
    borderRadius: '6px',
    padding: '4px 8px',
    fontSize: '12px',
    color: '#64748b',
    cursor: 'pointer',
  },
  pageActive: {
    backgroundColor: 'var(--c4w-color-primary)',
    borderColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
    fontWeight: 700,
  },
  exportContainerCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    padding: '24px',
    minHeight: '400px',
    display: 'flex',
    flexDirection: 'column',
  },
  exportInstruction: {
    fontSize: '14px',
    color: '#64748b',
    marginBottom: '24px',
  },
  exportOptionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '24px',
  },
  exportOptionCard: {
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '20px',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  exportCardHeader: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: '16px',
  },
  exportCardIconArea: {
    height: '80px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docIconBox: {
    position: 'relative',
  },
  plusIconBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: 'var(--c4w-color-primary)',
    color: '#fff',
    borderRadius: '50%',
    width: '16px',
    height: '16px',
    fontSize: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exportCardFooter: {
    fontSize: '12px',
    color: '#64748b',
    marginTop: '16px',
  },
  newCf4HeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  backButton: {
    border: 'none',
    backgroundColor: 'transparent',
    color: 'var(--c4w-color-primary)',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  newCf4Title: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#0f172a',
    margin: 0,
  },
  patientTableWrapper: {
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  newCf4FooterRow: {
    display: 'flex',
    justifyContent
    : 'flex-end',
    gap: '12px',
    marginTop: '20px',
  },
  /** Footer that also reports how many rows are queued for export. */
  newCf4FooterRowSpread: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    marginTop: '20px',
  },
  newCf4FooterActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  selectionCount: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#475569',
  },
  cancelBtn: {
    border: '1px solid #cbd5e1',
    backgroundColor: '#ffffff',
    color: '#475569',
    padding: '8px 16px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  proceedBtn: {
    backgroundColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
    border: 'none',
    padding: '8px 16px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  uploadHeaderArea: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    marginBottom: '16px',
  },
  uploadCloudCircle: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    backgroundColor: '#f1f5f9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadTitle: {
    margin: 0,
    fontSize: '14px',
    fontWeight: 700,
    color: '#0f172a',
  },
  uploadSubtitle: {
    margin: 0,
    fontSize: '12px',
    color: '#64748b',
  },
  uploadDivider: {
    border: 'none',
    borderTop: '1px solid #e2e8f0',
    margin: '0 0 16px 0',
  },
  dragDropZone: {
    border: '2px dashed #cbd5e1',
    borderRadius: '8px',
    padding: '32px',
    textAlign: 'center',
    marginBottom: '20px',
  },
  dragDropTitle: {
    margin: '0 0 4px 0',
    fontSize: '14px',
    fontWeight: 600,
    color: '#334155',
  },
  dragDropSubtitle: {
    margin: '0 0 16px 0',
    fontSize: '12px',
    color: '#94a3b8',
  },
  browseFileBtn: {
    backgroundColor: '#f1f5f9',
    color: '#334155',
    padding: '8px 16px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-block',
  },
  uploadedFileCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '12px',
  },
  pdfBadgeIcon: {
    backgroundColor: '#ef4444',
    color: '#fff',
    fontWeight: 700,
    fontSize: '10px',
    padding: '4px 6px',
    borderRadius: '4px',
  },
  uploadedFileName: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#0f172a',
  },
  uploadedFileMeta: {
    fontSize: '11px',
    color: '#64748b',
  },
  removeFileBtn: {
    background: 'none',
    border: 'none',
    color: '#94a3b8',
    cursor: 'pointer',
  },
  /** Validation banner shown when "Proceed to Summary" is pressed too early. */
  exportErrorBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    margin: '16px 0 0',
    padding: '10px 14px',
    borderRadius: '8px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#b91c1c',
    fontSize: '12px',
    fontWeight: 600,
  },
  /** Patient picker shown on the existing-CF4 upload step. */
  exportPatientPicker: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginBottom: '20px',
  },
  exportPatientLabel: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#334155',
  },
  exportPatientSelect: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid #cbd5e1',
    backgroundColor: '#ffffff',
    fontSize: '13px',
    color: '#0f172a',
    cursor: 'pointer',
  },
  exportPatientHint: {
    fontSize: '11px',
    color: '#94a3b8',
  },
  /** Step 3 — Course in the Ward Summary review. */
  summaryNavRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '10px',
  },
  summaryNavLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '11px',
    fontWeight: 700,
    color: '#334155',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  summaryNavCount: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '20px',
    height: '20px',
    padding: '0 6px',
    borderRadius: '999px',
    backgroundColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
    fontSize: '11px',
    fontWeight: 700,
  },
  summaryNavControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  summaryNavPosition: {
    minWidth: '42px',
    textAlign: 'center',
    fontSize: '12px',
    fontWeight: 700,
    color: '#475569',
    fontVariantNumeric: 'tabular-nums',
  },
  /** Clickable jumps to each patient queued for the summary. */
  summaryChips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginBottom: '18px',
  },
  summaryChip: {
    maxWidth: '220px',
    padding: '5px 12px',
    borderRadius: '999px',
    border: '1px solid #e2e8f0',
    backgroundColor: '#ffffff',
    color: '#475569',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  summaryChipActive: {
    /* Full shorthand: merging `border` (above) with a bare `borderColor` trips
       React's shorthand/longhand warning on every rerender. */
    border: '1px solid var(--c4w-color-primary)',
    backgroundColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
  },
  summarySourceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '18px',
  },
  summarySourceTag: {
    backgroundColor: 'var(--c4w-color-primary-soft)',
    color: 'var(--c4w-color-primary)',
    border: '1px solid #bfdbfe',
    borderRadius: '999px',
    padding: '4px 12px',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  summarySourceHint: {
    fontSize: '12px',
    color: '#64748b',
  },
  summaryPatientBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '18px',
    padding: '18px 20px',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    backgroundColor: '#f8fafc',
    marginBottom: '20px',
  },
  summaryAvatar: {
    width: '54px',
    height: '54px',
    borderRadius: '50%',
    backgroundColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    fontWeight: 700,
    flexShrink: 0,
  },
  summaryPatientName: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 700,
    color: '#0f172a',
  },
  summaryPatientMeta: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '24px',
    marginTop: '10px',
  },
  summaryMetaField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    minWidth: '76px',
  },
  summaryMetaLabel: {
    fontSize: '10px',
    fontWeight: 700,
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  summaryMetaValue: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#334155',
  },
  summaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: '20px',
    flex: 1,
    minHeight: 0,
  },
  summaryPanel: {
    border: '1px solid #e2e8f0',
    borderRadius: '12px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
  },
  summaryPanelHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 16px',
    backgroundColor: '#f1f5f9',
    borderBottom: '1px solid #e2e8f0',
  },
  summaryPanelTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#0f172a',
  },
  summaryPanelMeta: {
    fontSize: '11px',
    color: '#64748b',
    whiteSpace: 'nowrap',
  },
  summaryPanelBody: {
    padding: '16px',
    fontSize: '13px',
    lineHeight: 1.65,
    color: '#334155',
    whiteSpace: 'pre-wrap',
    overflowY: 'auto',
    maxHeight: '360px',
    flex: 1,
  },
  jsonPreview: {
    margin: 0,
    padding: '16px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    fontSize: '11.5px',
    lineHeight: 1.6,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
    overflow: 'auto',
    maxHeight: '360px',
    flex: 1,
  },
  /** Segmented JSON / PDF switch that sits in the summary panel header. */
  summaryPanelTabs: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '2px',
    borderRadius: '8px',
    backgroundColor: '#e2e8f0',
  },
  summaryTab: {
    border: 'none',
    /* `backgroundColor`, never the `background` shorthand — it is merged with
       `summaryTabActive`, and mixing the two warns on every rerender. */
    backgroundColor: 'transparent',
    borderRadius: '6px',
    /* Explicit padding — index.css has a global `button { padding: 8px 12px }`. */
    padding: '5px 10px',
    fontSize: '11px',
    fontWeight: 700,
    color: '#475569',
    cursor: 'pointer',
  },
  summaryTabActive: {
    backgroundColor: '#ffffff',
    color: '#0f172a',
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.12)',
  },
  /** Wrapper that lets a click-catching button sit over the PDF iframe. */
  pdfPreviewShell: {
    position: 'relative',
    display: 'flex',
    flex: 1,
    minHeight: 0,
  },
  /** Embedded PDF viewer. Needs a definite height — unlike the <pre>, an iframe
   *  has no intrinsic size, and `maxHeight: 360px` would collapse it. */
  pdfPreviewFrame: {
    width: '100%',
    height: '360px',
    border: 'none',
    backgroundColor: '#f8fafc',
    /* Clicks must reach `pdfPreviewHitArea`, not the viewer's own toolbar. */
    pointerEvents: 'none',
  },
  /** Transparent overlay that opens the enlarged viewer. */
  pdfPreviewHitArea: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    padding: '0 0 12px',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'zoom-in',
  },
  pdfPreviewHint: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '5px 12px',
    borderRadius: '9999px',
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    color: '#ffffff',
    fontSize: '11px',
    fontWeight: 700,
    pointerEvents: 'none',
  },
  pdfPreviewEmpty: {
    padding: '16px',
    fontSize: '12px',
    color: '#94a3b8',
  },
  summaryFooterRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '12px',
    marginTop: '20px',
  },
};

export const overviewStyles: Record<string, CSSProperties> = {
  overviewLayout: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '24px',
  },
  leftCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    padding: '20px',
  },
  cardTitle: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#0f172a',
    margin: '0 0 16px 0',
  },
  pagination: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    paddingTop: '16px',
  },
  paginationText: {
    fontSize: '12px',
    color: '#64748b',
  },
  paginationControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  pageButton: {
    minWidth: '32px',
    height: '32px',
    padding: '4px 8px',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    backgroundColor: '#ffffff',
    color: '#334155',
    fontSize: '12px',
    cursor: 'pointer',
  },
  pageActive: {
    backgroundColor: 'var(--c4w-color-primary)',
    borderColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
    fontWeight: 700,
  },
  evaluatorSelect: {
    width: '118px',
    padding: '5px 8px',
    border: '1px solid #9cc8ff',
    borderRadius: '6px',
    color: '#0066cc',
    backgroundColor: '#ffffff',
    fontSize: '11px',
  },
  rightColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
};
