import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  navIconImage: {
  width: '26px',
  height: '26px',
  marginRight: '10px',
  objectFit: 'contain',
  },
  tableCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
  },
  thRow: {
    backgroundColor: 'var(--c4w-color-primary-soft)',
    borderBottom: '1px solid var(--c4w-color-border)',
  },
  th: {
    padding: '12px 16px',
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--c4w-color-primary)',
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  tr: {
    borderBottom: '1px solid #f1f5f9',
  },
  td: {
    padding: '14px 16px',
  },
  requestActionCell: {
    width: '20%',
    textAlign: 'right',
    whiteSpace: 'nowrap',
  },
  reqId: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#0f172a',
  },
  docName: {
    fontSize: '13px',
    color: '#64748b',
  },
  dateText: {
    fontSize: '14px',
    color: '#334155',
  },
  timeText: {
    fontSize: '12px',
    color: '#94a3b8',
  },
  reviewBtn: {
    backgroundColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
    border: 'none',
    padding: '6px 16px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  paginationRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    borderTop: '1px solid #e2e8f0',
  },
  paginationText: {
    fontSize: '12px',
    color: '#64748b',
  },
  paginationControls: {
    display: 'flex',
    gap: '4px',
    alignItems: 'center',
  },
  pageArrowBtn: {
    border: '1px solid #e2e8f0',
    backgroundColor: '#ffffff',
    borderRadius: '4px',
    padding: '4px 8px',
    cursor: 'pointer',
  },
  pageNumberBtn: {
    minWidth: '32px',
    height: '32px',
    border: '1px solid #e2e8f0',
    backgroundColor: 'transparent',
    borderRadius: '6px',
    padding: '4px 8px',
    fontSize: '12px',
    color: '#64748b',
    cursor: 'pointer',
  },
  pageActive: {
    backgroundColor: 'var(--c4w-color-primary)',
    borderColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
    fontWeight: 700,
  },
  exportContainerCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    padding: '24px',
    minHeight: '400px',
    display: 'flex',
    flexDirection: 'column',
  },
  exportInstruction: {
    fontSize: '14px',
    color: '#64748b',
    marginBottom: '24px',
  },
  exportOptionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '24px',
  },
  exportOptionCard: {
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '20px',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  exportCardHeader: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: '16px',
  },
  exportCardIconArea: {
    height: '80px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docIconBox: {
    position: 'relative',
  },
  plusIconBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: 'var(--c4w-color-primary)',
    color: '#fff',
    borderRadius: '50%',
    width: '16px',
    height: '16px',
    fontSize: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exportCardFooter: {
    fontSize: '12px',
    color: '#64748b',
    marginTop: '16px',
  },
  newCf4HeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  backButton: {
    border: 'none',
    backgroundColor: 'transparent',
    color: 'var(--c4w-color-primary)',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  newCf4Title: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#0f172a',
    margin: 0,
  },
  patientTableWrapper: {
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  newCf4FooterRow: {
    display: 'flex',
    justifyContent
    : 'flex-end',
    gap: '12px',
    marginTop: '20px',
  },
  cancelBtn: {
    border: '1px solid #cbd5e1',
    backgroundColor: '#ffffff',
    color: '#475569',
    padding: '8px 16px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  proceedBtn: {
    backgroundColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
    border: 'none',
    padding: '8px 16px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  uploadHeaderArea: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    marginBottom: '16px',
  },
  uploadCloudCircle: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    backgroundColor: '#f1f5f9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadTitle: {
    margin: 0,
    fontSize: '14px',
    fontWeight: 700,
    color: '#0f172a',
  },
  uploadSubtitle: {
    margin: 0,
    fontSize: '12px',
    color: '#64748b',
  },
  uploadDivider: {
    border: 'none',
    borderTop: '1px solid #e2e8f0',
    margin: '0 0 16px 0',
  },
  dragDropZone: {
    border: '2px dashed #cbd5e1',
    borderRadius: '8px',
    padding: '32px',
    textAlign: 'center',
    marginBottom: '20px',
  },
  dragDropTitle: {
    margin: '0 0 4px 0',
    fontSize: '14px',
    fontWeight: 600,
    color: '#334155',
  },
  dragDropSubtitle: {
    margin: '0 0 16px 0',
    fontSize: '12px',
    color: '#94a3b8',
  },
  browseFileBtn: {
    backgroundColor: '#f1f5f9',
    color: '#334155',
    padding: '8px 16px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-block',
  },
  uploadedFileCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '12px',
  },
  pdfBadgeIcon: {
    backgroundColor: '#ef4444',
    color: '#fff',
    fontWeight: 700,
    fontSize: '10px',
    padding: '4px 6px',
    borderRadius: '4px',
  },
  uploadedFileName: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#0f172a',
  },
  uploadedFileMeta: {
    fontSize: '11px',
    color: '#64748b',
  },
  removeFileBtn: {
    background: 'none',
    border: 'none',
    color: '#94a3b8',
    cursor: 'pointer',
  },
};

export const overviewStyles: Record<string, CSSProperties> = {
  overviewLayout: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '24px',
  },
  leftCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    padding: '20px',
  },
  cardTitle: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#0f172a',
    margin: '0 0 16px 0',
  },
  pagination: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    paddingTop: '16px',
  },
  paginationText: {
    fontSize: '12px',
    color: '#64748b',
  },
  paginationControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  pageButton: {
    minWidth: '32px',
    height: '32px',
    padding: '4px 8px',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    backgroundColor: '#ffffff',
    color: '#334155',
    fontSize: '12px',
    cursor: 'pointer',
  },
  pageActive: {
    backgroundColor: 'var(--c4w-color-primary)',
    borderColor: 'var(--c4w-color-primary)',
    color: '#ffffff',
    fontWeight: 700,
  },
  dateInput: {
    width: '112px',
    padding: '5px 6px',
    border: '1px solid #e2e8f0',
    borderRadius: '4px',
    color: '#0f172a',
    fontSize: '10px',
  },
  aiCard: {
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
  },
  aiHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 14px',
    backgroundColor: '#f1eaff',
  },
  aiTitle: {
    color: '#7c00b8',
    fontSize: '11px',
    fontWeight: 600,
  },
  aiStatus: {
    padding: '4px 18px',
    borderRadius: '6px',
    backgroundColor: '#d3a0f5',
    color: '#7c00b8',
    fontSize: '11px',
    fontWeight: 600,
  },
  aiSummary: {
    margin: 0,
    padding: '8px 14px',
    color: '#0f172a',
    fontSize: '11px',
    lineHeight: 1.35,
  },
  aiActions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0 14px 9px',
  },
  evaluatorSelect: {
    width: '118px',
    padding: '5px 8px',
    border: '1px solid #9cc8ff',
    borderRadius: '6px',
    color: '#0066cc',
    backgroundColor: '#ffffff',
    fontSize: '11px',
  },
  rightColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  ordersCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    padding: '20px',
  },
  ordersHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  arrowNavBtn: {
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    color: '#64748b',
  },
  timelineContainer: {
    position: 'relative',
    paddingLeft: '120px',
  },
  timelineLine: {
    position: 'absolute',
    left: '110px',
    top: 0,
    bottom: 0,
    width: '2px',
    backgroundColor: '#e2e8f0',
  },
  timelineItem: {
    position: 'relative',
    marginBottom: '20px',
  },
  timelineMeta: {
    position: 'absolute',
    left: '-120px',
    width: '100px',
    textAlign: 'right',
    fontSize: '11px',
  },
  timelineDot: {
    position: 'absolute',
    left: '-14px',
    top: '4px',
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: 'var(--c4w-color-primary)',
  },
  orderBox: {
    backgroundColor: '#f8fafc',
    borderRadius: '8px',
    padding: '12px',
    border: '1px solid #e2e8f0',
  },
};
