export enum Role {
  PHYSICIAN = 'PHYSICIAN',
  NURSE = 'NURSE',
  CLAIMS_PROCESSOR = 'CLAIMS_PROCESSOR',
  ADMIN = 'ADMIN',
}

export enum OrderType {
  MEDICATION = 'MEDICATION',
  ADMISSION = 'ADMISSION',
  DISCHARGE = 'DISCHARGE',
  DIAGNOSTIC = 'DIAGNOSTIC',
  OTHER = 'OTHER',
}

export enum OrderEnteredBy {
  PHYSICIAN = 'PHYSICIAN',
  NURSE_ON_BEHALF = 'NURSE_ON_BEHALF',
}

export enum SummaryStatus {
  DRAFT_AI = 'DRAFT_AI',
  DRAFT_EDITED = 'DRAFT_EDITED',
  APPROVED = 'APPROVED',
}

export enum ClaimStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  NEEDS_PHYSICIAN_VALIDATION = 'NEEDS_PHYSICIAN_VALIDATION',
  VALIDATED = 'VALIDATED',
  CF4_GENERATED = 'CF4_GENERATED',
}
